sudo: false
dist: trusty
language: python
install:
  - if [ -d wheelhouse ]; then mv wheelhouse wheelhouse.old; fi
  - pip wheel --wheel-dir wheelhouse -r requirements.txt --no-cache-dir --find-links wheelhouse.old
  - pip install --no-index --find-links wheelhouse -r requirements.txt
python:
  - '2.7'
  - '3.5'
script:
  - flake8 *.py
  - python -m unittest -v test_simplecpreprocessor
  - python setup.py bdist_wheel
cache:
  directories:
    - wheelhouse
git:
  depth: 3
deploy:
  skip_cleanup: true
  provider: script
  script: twine upload dist/*
  on:
    tags: true
    python: 3.5
