sudo: false
dist: trusty
language: python
install: ./install_deps
python:
  - '2.7'
  - '3.5'
script: ./build
cache:
  directories:
    - wheelhouse
git:
  depth: 3
deploy:
  skip_cleanup: true
  provider: script
  script: twine upload dist/*
  on:
    tags: true

