sudo: false
language: python
python:
- '2.7'
- '3.4'
install: pip install pyflakes
script: python -m unittest -v test_simplecpreprocessor && pyflakes simplecpreprocessor.py
deploy:
  provider: pypi
  user: nanonyme-ci
  distributions: bdist_wheel
  password:
    secure: usnDJdmEsZ3hoF01OkqryxvwwY4gbN1JfQmEmlkk6zVcBjJNUc31NWxuF4AN/G/MGa2kXm2tqEWmWj4qWZk0C9ySUsMU1WolExoi4ZNnGRgqiVHFaCIL8GzytQa+H3qIARevEwZIUIPikilo714b8Pj2sdLPmu365dXDEQmX8qRBlowYhkh0trtJgvDwr0DnyqzjeRX7g/Bwas8jDa2JKa/NsPAZrrt8trs+0C88sv0MoMf/tRcs9J9yradFrLIR/g4lW/MciKNIfqPUsEUiyUHTPjgL5NzCh0ipDdfxri4SJ598ujBUIzi1e1T/gRWKPRDT09iATy0EIZZAl8N7F9FM4kOiiJbMXh7Xst/Uv2kuLhPZZmC2GnqpgNCvXE4gs6paYhuzaUZN0XTUbBMTMYQfMxrYlPoedbkK8WLbHTcbGEFQA3DSuwFarogvDKDqbWVUfz1c4kAoSiIz6+kjLrWF3gj0sJTlCqTpDlXW2ol98PUDGolH7iRWS0d1CJ/T8me2fyp2Difc5sjbTukqgnxxkncE5AcVatvToRCeyhltuJvpbkThvNWrlJP7sMWxCz+fo/3CVgP2BL3cUgry95pFCCjIYfxITXflx+T5o9Msh0De/Ro/4u/QH5WyIvwYSzJpWsaxLuQsZRcKMhfkjSEd88diCR2ynWwzhL7Cn/c=
  on:
    tags: true